#!/usr/bin/env python3

def create_file():
    name = input("What is your name? ")
    with open(f"{name}.txt", "w") as f:
        f.write(f"My name is {name}.")


def helloWorld():
   print('Hello World')

helloWorld()
